<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.packt</groupId>
  <artifactId>book</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Spring Boot 3.0 Cookbook</name>
  <packaging>pom</packaging>

  <modules>
    <module>chapter1/recipe1-1</module>
    <module>chapter1/recipe1-2</module>
    <module>chapter1/recipe1-3</module>
    <module>chapter1/recipe1-4</module>
    <module>chapter1/recipe1-5</module>

    <!-- <module>chapter2</module>
    <module>chapter3</module>
    <module>chapter4</module>
    <module>chapter5</module>
    <module>chapter6</module>
    <module>chapter7</module>
    <module>chapter8</module>
    <module>chapter9</module>
    <module>chapter10</module> -->
  </modules>

</project>
