<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.packt</groupId>
  <artifactId>book</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Spring Boot 3.0 Cookbook</name>
  <packaging>pom</packaging>

  <modules>
    <module>chapter1/recipe1-1</module>
    <module>chapter1/recipe1-2</module>
    <module>chapter1/recipe1-3</module>
    <module>chapter1/recipe1-4</module>
    <module>chapter1/recipe1-5</module>
    <module>chapter1/recipe1-6/albums</module>
    <module>chapter1/recipe1-6/football</module>
    <module>chapter1/recipe1-7/albums</module>
    <module>chapter1/recipe1-7/football</module>

    <!-- <module>chapter2/recipe2-1/footballauth</module>
    <module>chapter2/recipe2-2/footballauth</module>
    <module>chapter2/recipe2-2/footballresource</module>
    <module>chapter2/recipe2-3/footballauth</module>
    <module>chapter2/recipe2-3/footballresource</module>
    <module>chapter2/recipe2-4/footballauth</module>
    <module>chapter2/recipe2-4/footballresource</module>
    <module>chapter2/recipe2-4/footballui</module>
    <module>chapter2/recipe2-5/footballauth</module>
    <module>chapter2/recipe2-5/footballresource</module>
    <module>chapter2/recipe2-5/footballui</module>
    <module>chapter2/recipe2-6/footballauth</module>
    <module>chapter2/recipe2-6/footballresource</module>
    <module>chapter2/recipe2-6/footballui</module>
    <module>chapter2/recipe2-6/theresmore/footballresource</module>
    <module>chapter2/recipe2-6/theresmore/footballui</module> -->

   <!--  <module>chapter3/recipe3-1/footballobs</module>
    <module>chapter3/recipe3-2/footballobs</module>
    <module>chapter3/recipe3-3/footballobs</module>
    <module>chapter3/recipe3-4/footballclient</module>
    <module>chapter3/recipe3-4/footballobs</module>
    <module>chapter3/recipe3-5/footballclient</module>
    <module>chapter3/recipe3-5/footballobs</module>
    <module>chapter3/recipe3-6/footballclient</module>
    <module>chapter3/recipe3-6/footballobs</module>
    <module>chapter3/recipe3-7/footballclient</module>
    <module>chapter3/recipe3-7/footballobs</module>
    <module>chapter3/recipe3-8/footballclient</module>
    <module>chapter3/recipe3-8/footballobs</module> -->

   <!--  <module>chapter4/recipe4-1/registry</module>
    <module>chapter4/recipe4-2/albums</module>
    <module>chapter4/recipe4-2/football</module>
    <module>chapter4/recipe4-2/registry</module>
    <module>chapter4/recipe4-3/albums</module>
    <module>chapter4/recipe4-3/football</module>
    <module>chapter4/recipe4-3/registry</module>
    <module>chapter4/recipe4-3-experimental/albums</module> -->

    <!-- <module>chapter5/recipe5-1/footballpg</module>
    <module>chapter5/recipe5-2/footballpg</module> -->

    <module>chapter6/recipe6-1/footballmdb</module>
    <module>chapter6/recipe6-2/footballmdb</module>
    <module>chapter6/recipe6-3/footballmdb</module>
    <module>chapter6/recipe6-4/footballmdb</module>
    <module>chapter6/recipe6-5/footballmdb</module>
    <module>chapter6/recipe6-6/footballmdb</module>
    <module>chapter6/recipe6-7/footballcdb</module>
    <module>chapter6/recipe6-8/footballcdb</module>
    <module>chapter6/recipe6-9/footballcdb</module>
    <module>chapter6/recipe6-10/footballcdb</module>

    <!-- s<module>chapter9/recipe9-8/football</module> -->

    <!--
    <module>chapter4/recipe4-3-experimental/football</module>
    <module>chapter4/recipe4-3-experimental/registry</module>
    <module>chapter4/recipe4-3-new/albums</module>
    <module>chapter4/recipe4-3-new/football</module>
    <module>chapter4/recipe4-3-new/registry</module>
    <module>chapter4/recipe4-4/albums</module>
    <module>chapter4/recipe4-4/football</module>
    <module>chapter4/recipe4-4/gateway</module>
    <module>chapter4/recipe4-4/registry</module>
    -->
  </modules>

</project>
