<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.packt</groupId>
  <artifactId>book</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Spring Boot 3.0 Cookbook</name>
  <packaging>pom</packaging>

  <modules>
    <module>chapter1/recipe1-*/*</module>
    <module>chapter2/recipe2-*/*</module>
    <module>chapter3/recipe3-*/*</module>
    <module>chapter4/recipe4-*/*</module>
    <module>chapter5/recipe5-*/*</module>
    <module>chapter6/recipe6-*/*</module>
    <module>chapter7/recipe7-*/*</module>
    <module>chapter8/recipe8-*/*</module>
    <module>chapter9/recipe9-*/*</module>
    <module>chapter10/recipe10-*/*</module>
  </modules>

</project>
