spring:
  mongodb:
    host: localhost
    port: 27017
    username: packt
    password: packt
    database: football
    authentication-database: admin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
