name: recipe1-6
services:

  recipe1-6-albums:
    build: ./albums
    image: recipe1-6-albums
    ports:
      - '127.0.0.1:8081:8080'
    mem_limit: 512m

  recipe1-6-football:
    build: ./football
    image: recipe1-6-football
    ports:
      - '127.0.0.1:8080:8080'
    mem_limit: 512m
