spring:
    jpa:
        open-in-view: false
        show-sql: true
        # generate-ddl: true
    # sql:
    #     init:
    #         mode: always
    datasource:
        url: jdbc:postgresql://localhost:5433/football2
        username: packt
        password: packt
