services:
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '127.0.0.1:3000:3000'
  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=packt
      - POSTGRES_PASSWORD=packt
    ports:
      - '5432:5432'

  prometheus:
    image: prom/prometheus:main-distroless
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  # Use Cassandra instead of in-memory storage
  zipkin:
    image: ghcr.io/openzipkin/zipkin:${TAG:-latest}
    # Uncomment to enable request logging (TRACE shows query values)
    # command: --logging.level.com.datastax.oss.driver.internal.core.tracker.RequestLogger=TRACE
    depends_on:
      zipkin_storage:
        condition: service_healthy
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin_storage
      # Add the baked-in username and password for the zipkin-mysql image
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
      - JAVA_OPTS=-Xms2g -Xmx2g -XX:+ExitOnOutOfMemoryError
    ports:
      - '9411:9411'
  zipkin_storage:
    image: ghcr.io/openzipkin/zipkin-mysql:${TAG:-latest}
    container_name: mysql
