include:
  - docker-compose-redis.yml
services:
  football:
    image: football:0.0.1-SNAPSHOT
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresql:5432/football
      - spring.data.redis.host=redis
      - spring.data.redis.port=6379
      - management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
    ports:
      - '8080:8080'
  postgresexporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    environment:
      - DATA_SOURCE_NAME=postgresql://packt:packct@postgresql:5432/postgres?sslmode=disable
    ports:
      - '9187:9187'
