spring:
  mongodb:
    uri: ${MONGODB_URI:mongodb://${MONGO_INITDB_ROOT_USERNAME:packt}:${MONGO_INITDB_ROOT_PASSWORD:packt}@127.0.0.1:27017/football?authSource=admin&directConnection=true}
    database: football
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
