name: spring-boot-cookbook
services:
  db:
    image: postgres:18.3-alpine3.22
    environment:
      POSTGRES_USER: packt
      POSTGRES_PASSWORD: packt
      POSTGRES_DB: football
    ports:
      - '127.0.0.1:5432:5432'
    restart: always
  zipkin:
    image: openzipkin/zipkin:3-amd64
    ports:
      - '127.0.0.1:9411:9411'
    restart: always
  mongo:
    image: mongo:7.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: packt
      MONGO_INITDB_ROOT_PASSWORD: packt
      MONGO_INITDB_DATABASE: football
    ports:
      - '127.0.0.1:27017:27017'
    restart: always
  cassandra:
    image: cassandra:5.0.8
    environment:
      CASSANDRA_CLUSTER_NAME: football
      CASSANDRA_KEYSPACE: football
      CASSANDRA_USERNAME: packt
      CASSANDRA_PASSWORD: packt
    ports:
      - '127.0.0.1:9042:9042'
    restart: always
